package model.cards;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.Data;
import model.Game;
import model.Player;

@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "action",
        visible = true
)
@JsonSubTypes({
        @JsonSubTypes.Type(value = MoveCard.class,   name = "MOVE"),
        @JsonSubTypes.Type(value = MoneyCard.class,  name = "GET_MONEY"),
        @JsonSubTypes.Type(value = MoneyCard.class,  name = "PAY"),
        @JsonSubTypes.Type(value = VariablePayCard.class, name = "PAY")
})
@Data
public abstract class Card {
        private int id;
        private String description;
        private ActionType action;

        public Card() {}

        // getters & setters are generated by Lombok

        // To apply the action to the player:
        public abstract void apply(Game game, Player player);

}
